server:
  port: 9090
  servlet:
    context-path: /

spring:
  application:
    name: realtime

  #h2:
    #console:
    #enabled: true
    #path: /h2-console

  datasource:
    url: jdbc:mysql://database-realtime.c9ic82u8gyj5.ap-northeast-2.rds.amazonaws.com:3306/toyproject?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Realtime!213!

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.vibe.realtime: DEBUG
    org.hibernate.SQL: DEBUG